window.STORY_LIBRARY = {
  "stories": [
    {
      "id": "freja-astrid",
      "title": "Freja & Astrid",
      "subtitle": "A parallel bilingual story",
      "languages": {
        "left": "Dansk",
        "right": "English"
      },
      "summary": "The rain falls on the roof of Freya's cave. Freya sits in her chair. She reads. She has been reading all morning. There are books on the table. There are books on the floor. There are boo...",
      "tags": [
        "parallel text",
        "Danish",
        "English"
      ],
      "updated": "2026-06-18",
      "chapters": [
        {
          "title": "Kapitel 1",
          "passages": [
            {
              "da": "Regnen falder på taget af Frejas hule. Freja sidder i sin stol. Hun læser. Hun har læst hele morgenen. Der ligger bøger på bordet. Der ligger bøger på gulvet. Der ligger bøger overalt. Freja vender en side. Så hører hun en lyd. Bank. Bank. Hun ser op. Der kommer et lille smil på hendes ansigt. Hun lægger bogen fra sig. \"Kom ind,\" siger hun. Døren åbner. Astrid står udenfor. Hendes hår er vådt. Hendes kappe er våd. Hendes støvler er meget våde. \"Det regner,\" siger Astrid. \"Ja,\" siger Freja.",
              "en": "The rain falls on the roof of Freya's cave. Freya sits in her chair. She reads. She has been reading all morning. There are books on the table. There are books on the floor. There are books everywhere. Freya turns a page. Then she hears a sound. Knock. Knock. She looks up. A small smile comes to her face. She puts the book down. \"Come in,\" she says. The door opens. Astrid is standing outside. Her hair is wet. Her cloak is wet. Her boots are very wet. \"It's raining,\" Astrid says. \"Yes,\" Freya says."
            },
            {
              "da": "Astrid ser på hende. Freja ser på Astrid. Så begynder Astrid at grine. \"Jeg ved ikke, hvorfor jeg sagde det.\" \"Nej,\" siger Freja. \"Det kunne jeg heller ikke forstå.\" Astrid træder ind. Freja lukker døren. \"Vil du have te?\" spørger Freja. Astrids ansigt bliver lyst. \"Altid.\" Freja går hen til kedlen. Astrid tager sin kappe af. Hun hænger den ved døren. Derefter sætter hun sig. Det er hendes stol. Ingen har sagt det. Men det er hendes stol. Hun sidder altid der. Freja laver te. Astrid ser på hende. Freja har mørkt hår i dag. Eller måske har hun altid mørkt hår",
              "en": "Astrid looks at her. Freya looks at Astrid. Then Astrid starts laughing. \"I don't know why I said that.\" \"No,\" Freya says. \"I couldn't understand that either.\" Astrid enters. Freya closes the door. \"Do you want some tea?\" Freya asks. Astrid's face brightens. \"Always.\" Freya goes to the kettle. Astrid takes off her cloak. She hangs it by the door.Then she sits down. It's her chair. No one has said so. But it's her chair. She always sits there. Freja is making tea. Astrid looks at her. Freja has dark hair today. Or maybe she always has dark hair."
            },
            {
              "da": ". Astrid tænker ikke så klart. Ikke når Freja er tæt på. \"Er du sulten?\" spørger Freja. \"Ja.\" \"Jeg har småkager.\" \"Jeg elsker dig.\" Freja stopper. Astrid stopper. Rummet bliver stille. Regnen falder udenfor. Astrids øjne bliver store. \"Jeg mener...\" Hun rødmer. \"Jeg elsker småkager.\" Freja ser på hende. Så smiler hun. \"Det ved jeg.\" Astrid lægger hovedet ned på bordet. \"Jeg vil grave et hul og bo der.\" Freja sætter teen foran hende. \"Du kan bo her.\" Astrid løfter hovedet. \"Virkelig?\" \"Ja.\" Freja sætter sig. \"Men du skal betale husleje.\" Astrid ser bekymret ud. \"Hvor meget?\" Freja tager sin kop op. \"En småkage om dagen.\" Astrid smiler. Det er en god aftale. De drikker te sammen. Udenfor regner det stadig. Indenfor er der varmt. Ingen af dem har lyst til at være andre steder.",
              "en": "Astrid isn't thinking clearly. Not when Freja is close. \"Are you hungry?\" Freja asks. \"Yes.\" \"I have cookies.\" \"I love you.\" Freja stops. Astrid stops. The room goes quiet. The rain is falling outside. Astrid's eyes widen. \"I mean...\" She blushes. \"I love cookies.\" Freja looks at her. Then she smiles. \"I know.\" Astrid puts her head down on the table. \"I want to dig a hole and live there.\" Freja puts the tea in front of her. \"You can live here.\" Astrid raises her head. \"Really?\" \"Yes.\" Freja sits down. \"But you have to pay rent.\" Astrid looks worried. \"How much?\" Freja picks up her cup. \"A cookie a day.\" Astrid smiles. It's a good deal. They drink tea together. It's still raining outside. It's warm inside. Neither of them wants to be anywhere else"
            }
          ]
        },
        {
          "title": "Kapitel 2",
          "passages": [
            {
              "da": "For første gang i flere dage regner det ikke. Astrid står udenfor Frejas hule. Hun banker på døren. Freja åbner næsten med det samme. \"Godmorgen,\" siger Astrid. \"Godmorgen,\" siger Freja. Astrid smiler. \"Vil du med til markedet?\" Freja tænker et øjeblik. \"Der kommer mange mennesker.\" \"Ja.\" \"Og meget larm.\" \"Ja.\" \"Og børn.\" \"Ja.\" Freja sukker. Astrid griner. \"Så det er et ja?\" \"Jeg ved ikke, hvorfor jeg siger ja til dig.\" \"Det ved jeg heller ikke.\" Freja lukker døren bag sig. De begynder at gå. Stien fører ned mod landsbyen. Træerne bevæger sig i vinden. Fuglene synger. Det er en smuk dag. Astrid går lidt foran. Freja ser på hende. Astrid vender sig om. \"Hvad?\" \"Ingenting.\" \"Du så på mig.\" \"Nej.\" Astrid smiler. Freja ser væk. Efter noget tid kommer de til landsbyen. Markedet er allerede fyldt. Folk taler. Børn løber. Handlende råber. Astrid ser glad ud. Freja ser træt ud. \"Vi har været her i fem sekunder,\" siger Astrid. \"Jeg er allerede færdig.\" Astrid griner. De går mellem boderne. Der er frugt. Der er grøntsager. Der er blomster. Der er bøger. Freja stopper. Astrid stopper også. \"Åh nej,\" siger Astrid. \"Hvad?\" \"Du har set bøger.\" Freja går allerede mod boden. Astrid følger efter. Der ligger gamle bøger på et bord. Freja tager en op. Så en til. Så en tredje. \"Hvor mange bøger har du brug for?\" spørger Astrid. Freja ser overrasket ud. \"Brug for?\" Astrid nikker. Freja tænker. \"Alle sammen.\" Astrid begynder at grine.",
              "en": "For the first time in days it is not raining. Astrid is standing outside Freja's cave. She knocks on the door. Freja opens almost immediately. \"Good morning,\" Astrid says. \"Good morning,\" Freja says. Astrid smiles. \"Do you want to go to the market?\" Freja thinks for a moment. \"There will be a lot of people coming.\" \"Yes.\" \"And a lot of noise.\" \"Yes.\" \"And children.\" \"Yes.\" Freja sighs. Astrid laughs. \"So it's a yes?\" \"I don't know why I'm saying yes to you.\" \"I don't know that either.\" Freja closes the door behind her. They start walking. The path leads down towards the village. The trees move in the wind. The birds are singing. It's a beautiful day. Astrid walks a little ahead. Freja looks at her. Astrid turns around. \"What?\" \"Nothing.\" \"You were looking at me.\" \"No.\" Astrid smiles. Freja looks away. After some time they reach the village. The market is already full. People are talking. Children are running. Shopkeepers are shouting. Astrid looks happy. Freja looks tired. \"We've been here for five seconds,\" Astrid says. \"I'm already done.\" Astrid laughs. They walk between the stalls. There's fruit. There's vegetables. There's flowers. There's books. Freja stops. Astrid stops too. \"Oh no,\" Astrid says. \"What?\" \"You've seen books.\" Freja is already walking towards the stall. Astrid follows. There are old books on a table. Freja picks one up. Then another. Then a third. \"How many books do you need?\" Astrid asks. Freja looks surprised. \"Need for?\" Astrid nods. Freja thinks. \"All of them.\" Astrid starts laughing."
            },
            {
              "da": "En time senere går de stadig rundt. Astrid bærer en pose. Freja bærer tre. \"Det er ikke fair,\" siger Astrid. \"Du købte bøgerne.\" \"Ja.\" \"Men jeg bærer dem.\" \"Ja.\" Astrid ryster på hovedet. Pludselig stopper hun. \"Vent.\" Hun peger. Der står en lille bod ved vejen. Der dufter af kanel. Der dufter af sukker. Der dufter af varme boller. Astrid ser lykkelig ud. \"Freja.\" \"Nej.\" \"Freja.\" \"Nej.\" \"Freja.\" Freja lukker øjnene. \"Fint.\" Astrid køber en bolle. Så køber Freja en. De sætter sig på en bænk. Astrid tager en bid. Hendes øjne bliver store. \"Det er den bedste bolle i verden.\" \"Det siger du hver gang.\" \"Fordi det er sandt hver gang.\" Freja tager en bid af sin egen. Astrid ser på hende. \"Hvad?\" \"Ingenting.\" \"Du ser mærkelig ud.\" Astrid smiler. \"Du har sukker på næsen.\" Freja fryser. \"Hvad?\" \"Sukker.\" \"Hvor?\" Astrid læner sig frem. Meget forsigtigt tørrer hun det væk. Freja bliver helt stille. Astrid bliver også stille. Pludselig virker bollen meget interessant. Freja ser på sin te. Der er ingen te. Hun ser alligevel ned. Efter et øjeblik rejser Astrid sig. \"Skal vi gå videre?\" Freja nikker. \"Ja.\" De begynder at gå igen. Men nu går de lidt tættere på hinanden end før.",
              "en": "An hour later they are still walking around. Astrid is carrying one bag. Freja is carrying three. \"That's not fair,\" Astrid says. \"You bought the books.\" \"Yes.\" \"But I'm carrying them.\" \"Yes.\" Astrid shakes her head. Suddenly she stops. \"Wait.\" She points. There's a little stall by the road. It smells of cinnamon. It smells of sugar. It smells of warm buns. Astrid looks happy. \"Freja.\" \"No.\" \"Freja.\" \"No.\" \"Freja.\" Freja closes her eyes. \"Fine.\" Astrid buys a bun. Then Freja buys one. They sit down on a bench. Astrid takes a bite. Her eyes get big. \"It's the best bun in the world.\" \"You say that every time.\" \"Because it's true every time.\" Freja takes a bite of her own. Astrid looks at her. \"What?\" \"Nothing.\" \"You look strange.\" Astrid smiles. \"You have sugar on your nose.\" Freja freezes. \"What?\" \"Sugar.\" \"Where?\" Astrid leans forward. Very carefully she wipes it away. Freja becomes completely silent. Astrid also becomes silent. Suddenly the bun seems very interesting. Freja looks at her tea. There is no tea. She looks down anyway. After a moment Astrid stands up. \"Should we go on?\" Freja nods. \"Yes.\" They start walking again. But now they are walking a little closer to each other than before."
            }
          ]
        },
        {
          "title": "Kapitel 3",
          "passages": [
            {
              "da": "Solen er lige stået op. Hun strækker sig. Det bliver en god dag. Måske. Hun tager sine støvler på. Så går hun mod Frejas hule. Hun når næsten frem. Så hører hun en lyd. \"Pib.\" Astrid stopper. Hun ser sig omkring. \"Pib.\" Lyden kommer fra en busk. Astrid går nærmere. \"Hallo?\" Busken ryster. Et lille hoved kommer frem. Astrid blinker. Hovedet blinker tilbage. Det er en drage. En meget lille drage. Den er ikke større end en kat. Måske mindre. Dragen nyser. En lille sky af røg kommer ud af dens næse. Astrid smiler. \"Hej.\" Dragen ser på hende. \"Hej.\" Dragen siger ingenting. \"Du er ikke så god til samtaler.\" Dragen nyser igen. Astrid holder armene frem. Dragen tænker et øjeblik. Så hopper den op i hendes arme. \"Åh.\" Astrid ser overrasket ud. \"Du er tungere, end du ser ud.\" Dragen gaber. Så lægger den hovedet mod hendes skulder. Astrid smiler. \"Okay.\" Hun ser mod hulen. \"Vi må finde Freja.\"",
              "en": "The sun has just risen. She stretches. It’s going to be a good day. Maybe. She puts on her boots. Then she walks towards Freya’s cave. She’s almost there. Then she hears a sound. “Peep.” Astrid stops. She looks around. “Peep.” The sound comes from a bush. Astrid walks closer. “Hello?” The bush shakes. A small head emerges. Astrid blinks. The head blinks back. It’s a dragon. A very small dragon. It’s no bigger than a cat. Maybe smaller. The dragon sneezes. A small cloud of smoke comes out of its nose. Astrid smiles. “Hello.” The dragon looks at her. “Hello.” The dragon says nothing. “You’re not very good at conversation.” The dragon sneezes again. Astrid holds out her arms. The dragon thinks for a moment. Then it jumps into her arms. “Oh.” Astrid looks surprised. “You’re heavier than you look.” The dragon yawns. Then it rests its head against her shoulder. Astrid smiles. “Okay.” She looks towards the cave. \"We have to find Freya.\""
            },
            {
              "da": "Freja åbner døren. Astrid står udenfor. Der sidder en drage på hendes skulder. Freja stirrer. Astrid smiler. \"Godmorgen.\" Freja stirrer stadig. \"Der er en drage på dig.\" \"Ja.\" \"Hvorfor?\" Astrid tænker. \"Jeg tror, den valgte mig.\" Freja ser på dragen. Dragen ser på Freja. Dragen stikker tungen ud. Freja ser fornærmet ud. Astrid begynder at grine.",
              "en": "Freja opens the door. Astrid is standing outside. There is a dragon sitting on her shoulder. Freja stares. Astrid smiles. \"Good morning.\" Freja is still staring. \"There is a dragon on you.\" \"Yes.\" \"Why?\" Astrid thinks. \"I think it chose me.\" Freja looks at the dragon. The dragon looks at Freja. The dragon sticks out its tongue. Freja looks offended. Astrid starts to laugh."
            },
            {
              "da": "Senere sidder de ved bordet. Dragen ligger midt på bordet. Den sover. Freja læser. Astrid drikker te. Alt er stille. Så åbner dragen et øje. Den ser på Freja. Den ser på Astrid. Den ser på Freja igen. Så rejser den sig. Astrid holder vejret. \"Hvad laver den?\" Dragen hopper ned fra bordet. Den går hen over gulvet. Freja følger den med øjnene. Dragen stopper ved hendes stol. Så hopper den op. Direkte op i hendes skød. Freja fryser. Astrid fryser. Dragen vender sig rundt. En gang. To gange. Tre gange. Så lægger den sig til rette. Og falder i søvn. Freja stirrer ned. Dragen snorker. Meget små snork. Astrid smiler. \"Jeg troede, den ikke kunne lide dig.\" \"Det troede jeg også.\" Freja løfter forsigtigt en hånd. Hun klapper dragen på hovedet. Dragen laver en glad lyd. Astrid smiler endnu mere. Freja ser op. \"Hvad?\" \"Ingenting.\" \"Du smiler.\" \"Ja.\" \"Hvorfor?\" Astrid ser på dragen. Så på Freja. \"Jeg tror bare, det er et godt syn.\" Freja mærker, at hendes kinder bliver varme. \"Det er bare en drage.\" \"Ja.\" Astrid tager en slurk te. \"Det er det.\"",
              "en": "Later they sit at the table. The dragon lies in the middle of the table. It sleeps. Freya reads. Astrid drinks tea. Everything is quiet. Then the dragon opens one eye. It looks at Freya. It looks at Astrid. It looks at Freya again. Then it stands up. Astrid holds her breath. \"What is it doing?\" The dragon jumps off the table. It walks across the floor. Freya follows it with her eyes. The dragon stops at her chair. Then it jumps up. Straight onto her lap. Freya freezes. Astrid freezes. The dragon turns around. Once. Twice. Three times. Then it settles down. And falls asleep. Freya stares down. The dragon snores. Very small snores. Astrid smiles. \"I thought it didn't like you.\" \"I thought so too.\" Freya carefully raises a hand. She pats the dragon on the head. The dragon makes a happy sound. Astrid smiles even more. Freya looks up. \"What?\" \"Nothing.\" \"You're smiling.\" \"Yes.\" \"Why?\" Astrid looks at the dragon. Then at Freja. \"I just think it's a good sight.\" Freja feels her cheeks heat up. \"It's just a dragon.\" \"Yes.\" Astrid takes a sip of tea. \"That's it."
            },
            {
              "da": "Om eftermiddagen går de gennem skoven. Dragen følger efter. Den løber. Den hopper. Den jagter sommerfugle. Den taber til sommerfuglene. Hver gang. \"Den er ikke særlig god til at være drage,\" siger Astrid. \"Nej.\" \"Den er sød.\" \"Ja.\" De går længere ind i skoven. Pludselig stopper dragen. Den løfter hovedet. Astrid stopper også. Freja lukker sin bog. Der kommer en lyd. Et dybt brøl. Dragen piber. Så løber den frem. Astrid og Freja følger efter. Mellem træerne står en stor drage. Meget stor. Den ser bekymret ud. Den lille drage løber direkte hen til den. Den store drage sænker hovedet. De rører næser. Den lille drage laver glade lyde. Astrid smiler. \"Det er dens mor.\" Freja nikker. \"Det tror jeg også.\" Den store drage ser på dem. Astrid vinker. \"Hej.\" Den store drage blinker langsomt. Så skubber den forsigtigt den lille drage frem. Den lille drage løber tilbage. Direkte hen til Freja. Freja ser overrasket ud. Dragen giver hendes hånd et lille skub med hovedet. Som om den siger tak. Så løber den tilbage til sin mor. Et øjeblik senere er de væk. Skoven bliver stille. Astrid og Freja står sammen. \"Jeg savner den allerede,\" siger Astrid. \"Det gør jeg også.\" De begynder at gå hjem. Efter nogle minutter siger Astrid: \"Hvis vi finder en anden drage, må vi beholde den.\" \"Nej.\" \"Hvis den er lille?\" \"Nej.\" \"Hvis den er sød?\" \"Nej.\" Astrid smiler. \"Hvis den vælger dig?\" Freja bliver stille. Så sukker hun. \"Så må vi tale om det.\" Astrid griner hele vejen hjem.",
              "en": "In the afternoon they walk through the forest. The dragon follows. It runs. It jumps. It chases butterflies. It loses to the butterflies. Every time. \"It's not very good at being a dragon,\" says Astrid. \"No.\" \"It's cute.\" \"Yes.\" They walk further into the forest. Suddenly the dragon stops. It raises its head. Astrid stops too. Freja closes her book. There's a sound. A deep roar. The dragon whistles. Then it runs forward. Astrid and Freja follow. Between the trees stands a big dragon. Very big. It looks worried. The little dragon runs straight towards it. The big dragon lowers its head. They touch noses. The little dragon makes happy noises. Astrid smiles. \"That's its mother.\" Freja nods. \"I think so too.\" The big dragon looks at them. Astrid waves. \"Hello.\" The big dragon blinks slowly. Then it carefully pushes the little dragon forward. The little dragon runs back. Straight towards Freja. Freja looks surprised. The dragon gives her hand a little nudge with its head. As if to say thank you. Then it runs back to its mother. A moment later they are gone. The forest becomes quiet. Astrid and Freja stand together. \"I miss it already,\" Astrid says. \"I do too.\" They start walking home. After a few minutes, Astrid says, \"If we find another dragon, we can keep it.\" \"No.\" \"If it's small?\" \"No.\" \"If it's cute?\" \"No.\" Astrid smiles. \"If it chooses you?\" Freja goes silent. Then she sighs. \"Then we have to talk about it.\" Astrid laughs all the way home."
            }
          ]
        },
        {
          "title": "Kapitel 4",
          "passages": [
            {
              "da": "Først falder der kun få dråber. Så kommer der flere. Og flere. Og flere. Ved middagstid regner det så meget, at Astrid næsten ikke kan se stien. \"Det er fint,\" siger hun. Det er ikke fint. Hendes kappe er våd. Hendes støvler er våde. Hendes hår er meget vådt. Hun tørrer regn væk fra øjnene. Så ser hun noget. Et hus. Eller næsten et hus. Måske en hytte. Måske en bunke træ med ambitioner. Astrid løber hen mod den.",
              "en": "At first, only a few drops fall. Then more. And more. And more. By noon, it's raining so hard that Astrid can barely see the path. \"It's fine,\" she says. It's not fine. Her cloak is wet. Her boots are wet. Her hair is very wet. She wipes the rain from her eyes. Then she sees something. A house. Or almost a house. Maybe a cabin. Maybe a pile of wood with ambitions. Astrid runs toward it."
            },
            {
              "da": "Taget holder stadig regnen ude. Det er det vigtigste. Astrid står i døren. Hun drypper på gulvet. \"Perfekt.\" Hun træder indenfor. Der er støv. Der er gamle møbler. Der er et bord. Der er en pejs. Der er også en anden person. Astrid stopper. Freja stopper. De stirrer på hinanden. Regnen trommer på taget. \"Åh.\" \"Åh.\" Astrid peger. \"Du er her.\" \"Ja.\" \"Jeg troede, jeg var den eneste person i skoven.\" Freja løfter et øjenbryn. \"Virkelig?\" \"Nej.\" \"Godt.\"",
              "en": "The roof is still keeping the rain out. That's the most important thing. Astrid stands in the doorway. She's dripping onto the floor. \"Perfect.\" She steps inside. There's dust. There's old furniture. There's a table. There's a fireplace. There's another person, too. Astrid stops. Freja stops. They stare at each other. The rain is drumming on the roof. \"Oh.\" \"Oh.\" Astrid points. \"You're here.\" \"Yes.\" \"I thought I was the only person in the forest.\" Freja raises an eyebrow. \"Really?\" \"No.\" \"Good.\""
            },
            {
              "da": "De tænder ild i pejsen. Varmen spreder sig langsomt. Astrid hænger sin kappe til tørre. Freja gør det samme. Et øjeblik senere sidder de ved pejsen. Regnen bliver ved. Og ved. Og ved. Astrid ser ud gennem vinduet. \"Jeg tror ikke, vi kommer hjem i dag.\" \"Nej.\" \"Så vi sidder fast.\" \"Ja.\" Astrid smiler. Freja ser mistænksom ud. \"Hvorfor smiler du?\" \"Jeg prøver bare at finde noget positivt.\" \"Hvad er det positive?\" Astrid ser på hende. Freja ser tilbage. Der går et øjeblik. Så rødmer Astrid. \"Pejsen.\" \"Pejsen.\" \"Ja.\" Freja nikker langsomt. \"Selvfølgelig.\"",
              "en": "They light a fire in the fireplace. The heat spreads slowly. Astrid hangs her coat out to dry. Freja does the same. A moment later they are sitting by the fireplace. The rain continues. And on. And on. Astrid looks out the window. \"I don't think we'll get home today.\" \"No.\" \"So we're stuck.\" \"Yes.\" Astrid smiles. Freja looks suspicious. \"Why are you smiling?\" \"I'm just trying to find something positive.\" \"What's the positive?\" Astrid looks at her. Freja looks back. A moment passes. Then Astrid blushes. \"The fireplace.\" \"The fireplace.\" \"Yes.\" Freja nods slowly. \"Of course.\""
            },
            {
              "da": "Senere finder Astrid et skab. Inde i skabet ligger der spil. Meget gamle spil. Astrid kommer løbende tilbage. \"Freja!\" Freja ser op fra sin bog. \"Hvad?\" \"Jeg har fundet skatte.\" \"Det tvivler jeg på.\" \"Spil er skatte.\" Freja sukker. En time senere taber hun for tredje gang. \"Det giver ingen mening.\" Astrid smiler. \"Jeg er meget dygtig.\" \"Du fandt reglerne på vejen.\" \"Detaljer.\" Freja lægger armene over kors. \"Jeg kræver revanche.\" \"Du taber igen.\" \"Det får vi at se.\" Hun taber igen.",
              "en": "Later, Astrid finds a cupboard. Inside the cupboard are games. Very old games. Astrid comes running back. \"Freja!\" Freja looks up from her book. \"What?\" \"I've found treasures.\" \"I doubt that.\" \"Games are treasures.\" Freja sighs. An hour later, she loses for the third time. \"That doesn't make sense.\" Astrid smiles. \"I'm very skilled.\" \"You found the rules on the way.\" \"Details.\" Freja crosses her arms. \"I demand revenge.\" \"You lose again.\" \"We'll see.\" She loses again."
            },
            {
              "da": "Det bliver mørkt. Regnen fortsætter. Vinden hyler udenfor. Indenfor er der varmt. Pejsen knitrer. Astrid sidder på gulvet. Freja sidder ved siden af. Ikke helt tæt. Men tættere end normalt. De taler. Om bøger. Om drager. Om landsbyen. Om dumme ting. Om vigtige ting. Om ingenting. Timerne går. Ingen lægger mærke til det.",
              "en": "It's getting dark. The rain continues. The wind howls outside. It's warm inside. The fireplace is crackling. Astrid is sitting on the floor. Freja is sitting next to her. Not quite close. But closer than usual. They talk. About books. About dragons. About the village. About stupid things. About important things. About nothing. The hours pass. No one notices."
            },
            {
              "da": "\"Freja?\" \"Ja?\" \"Hvorfor bor du alene?\" Freja bliver stille. Hun ser ind i flammerne. \"Jeg kan godt lide stilhed.\" Astrid nikker. Det giver mening. Lidt. \"Bliver du aldrig ensom?\" Freja tænker længe. Meget længe. Til sidst siger hun: \"Nogle gange.\" Astrid ser ned. \"Hm.\" \"Og dig?\" Astrid smiler svagt. \"Jeg bliver ensom hele tiden.\" Freja vender hovedet. \"Virkelig?\" Astrid nikker. \"Men det er bedre nu.\" Freja mærker igen varmen i sine kinder. \"Fordi du har venner?\" Astrid ser på hende. Kun på hende. \"Ja.\" Freja ser hurtigt tilbage mod pejsen. Det føles sikrere.",
              "en": "\"Freja?\" \"Yes?\" \"Why do you live alone?\" Freja falls silent. She looks into the flames. \"I like silence.\" Astrid nods. That makes sense. A little. \"Do you never get lonely?\" Freja thinks for a long time. A very long time. Finally she says: \"Sometimes.\" Astrid looks down. \"Hm.\" \"And you?\" Astrid smiles faintly. \"I get lonely all the time.\" Freja turns her head. \"Really?\" Astrid nods. \"But it's better now.\" Freja feels the heat in her cheeks again. \"Because you have friends?\" Astrid looks at her. Only at her. \"Yes.\" Freja quickly looks back at the fireplace. It feels safer."
            },
            {
              "da": "Senere den aften falder Astrid i søvn. Meget pludseligt. Midt i en sætning. Freja opdager det først, da der ikke kommer flere ord. Hun ser over. Astrids hoved hænger lidt til siden. Hun sover. Freja smiler. \"Imponerende.\" Hun finder et gammelt tæppe. Forsigtigt lægger hun det over Astrid. Astrid mumler noget. Freja læner sig nærmere. \"Hvad sagde du?\" Astrid mumler igen. Freja hører kun ét ord. \"Freja.\" Så sover Astrid videre. Freja bliver helt stille. Meget stille. Pejsen knitrer. Regnen falder. Og Freja kan pludselig ikke huske, hvad der stod i hendes bog.",
              "en": "Later that night, Astrid falls asleep. Very suddenly. In the middle of a sentence. Freja only notices it when no more words come. She looks over. Astrid's head hangs a little to the side. She's asleep. Freja smiles. \"Impressive.\" She finds an old blanket. She carefully places it over Astrid. Astrid mumbles something. Freja leans closer. \"What did you say?\" Astrid mumbles again. Freja hears only one word. \"Freja.\" Then Astrid goes back to sleep. Freja becomes completely silent. Very silent. The fireplace crackles. The rain falls. And Freja suddenly can't remember what was in her book."
            },
            {
              "da": "Næste morgen skinner solen. Regnen er væk. Skoven glitrer. Astrid strækker sig. \"Godmorgen.\" \"Godmorgen.\" De pakker deres ting. De går mod døren. Astrid stopper. \"Hm.\" \"Hvad?\" \"Jeg havde det faktisk ret hyggeligt.\" Freja smiler. \"Ja.\" Astrid åbner døren. Solen skinner på dem begge. \"Vi burde sidde fast i en hytte igen.\" Freja ryster på hovedet. \"Nej.\" \"En gang om måneden?\" \"Nej.\" \"Hver anden måned?\" \"Nej.\" Astrid griner. Freja gør sit bedste for ikke at smile. Hun fejler.",
              "en": "The next morning the sun is shining. The rain is gone. The forest is sparkling. Astrid stretches. \"Good morning.\" \"Good morning.\" They pack their things. They head for the door. Astrid stops. \"Hm.\" \"What?\" \"I actually had a nice time.\" Freja smiles. \"Yes.\" Astrid opens the door. The sun shines on both of them. \"We should be stuck in a cabin again.\" Freja shakes her head. \"No.\" \"Once a month?\" \"No.\" \"Every other month?\" \"No.\" Astrid laughs. Freja does her best not to smile. She fails."
            }
          ]
        },
        {
          "title": "Kapitel 5",
          "passages": [
            {
              "da": "Ingen regn. Ingen drager. Ingen eventyr. Bare en stille dag. Astrid synes, det er perfekt. Hun går gennem skoven. Under armen har hun en stak bøger. Meget tunge bøger. Meget, meget tunge bøger. \"Freja skylder mig te for det her.\" Hun tager et skridt. Så et til. Så et til. Bøgerne glider. Astrid kæmper. \"Jeg fortryder alt.\"",
              "en": "No rain. No dragons. No fairy tales. Just a quiet day. Astrid thinks it's perfect. She walks through the forest. Under her arm she has a stack of books. Very heavy books. Very, very heavy books. \"Freja owes me tea for this.\" She takes a step. Then another. Then another. The books slip. Astrid struggles. \"I regret everything.\""
            },
            {
              "da": "Freja venter udenfor biblioteket. Det er en gammel bygning. Den er lille. Men den er fyldt med bøger. For Freja er det næsten et slot. Hun ser Astrid komme gående. Eller vaklende. Mest vaklende. \"Har du brug for hjælp?\" spørger Freja. \"Nej.\" En bog falder. Astrid sparker den ved et uheld. En anden bog falder. \"Ja.\" Freja tager halvdelen af bøgerne. Astrid sukker af lettelse. \"Du er en helt.\" \"Det ved jeg.\" Astrid stirrer. Freja fortsætter med at gå. Et lille smil gemmer sig i hendes ansigt.",
              "en": "Freja is waiting outside the library. It's an old building. It's small. But it's full of books. To Freja, it's almost a castle. She sees Astrid coming walking. Or staggering. Mostly staggering. \"Do you need help?\" Freja asks. \"No.\" A book falls. Astrid kicks it by accident. Another book falls. \"Yes.\" Freja takes half the books. Astrid sighs with relief. \"You're a hero.\" \"I know.\" Astrid stares. Freja continues walking. A small smile hides on her face."
            },
            {
              "da": "Bibliotekaren er gammel. Meget gammel. Hun ser over sine briller. Så ser hun på Astrid. Så på Freja. Så på Astrid igen. \"Hm.\" Astrid smiler. \"Hej.\" \"Hm.\" Freja sukker. Bibliotekaren nikker langsomt. \"Hm.\" Astrid ser forvirret ud. \"Hvorfor siger hun kun hm?\" \"Jeg ved det ikke,\" siger Freja. Det ved hun godt.",
              "en": "The librarian is old. Very old. She looks over her glasses. Then she looks at Astrid. Then at Freja. Then at Astrid again. \"Hm.\" Astrid smiles. \"Hi.\" \"Hm.\" Freja sighs. The librarian nods slowly. \"Hm.\" Astrid looks confused. \"Why does she only say hm?\" \"I don't know,\" says Freja. She knows."
            },
            {
              "da": "De afleverer bøgerne. Næsten alle bøgerne. Næsten. Bibliotekaren tæller. En. To. Tre. Fire. Hun stopper. \"Hm.\" Freja fryser. \"Hvad?\" \"Der mangler en bog.\" \"Det kan ikke passe.\" Bibliotekaren løfter et papir. \"Det passer.\" Freja tager papiret. Hendes øjne bliver store. \"Åh nej.\" Astrid ser bekymret ud. \"Hvad er der?\" Freja viser hende titlen. Astrid læser. Hun blinker. Hun læser igen. \"Historien om gamle svampe?\" \"Ja.\" \"Det er den manglende bog?\" \"Ja.\" Astrid prøver virkelig ikke at grine. Hun fejler.",
              "en": "They hand in the books. Almost all the books. Almost. The librarian counts. One. Two. Three. Four. She stops. \"Hm.\" Freja freezes. \"What?\" \"There's a book missing.\" \"That can't fit.\" The librarian holds up a piece of paper. \"That fits.\" Freja takes the paper. Her eyes widen. \"Oh no.\" Astrid looks worried. \"What's that?\" Freja shows her the title. Astrid reads. She blinks. She reads again. \"The story of old mushrooms?\" \"Yes.\" \"That's the missing book?\" \"Yes.\" Astrid really tries not to laugh. She fails."
            },
            {
              "da": "Jagten begynder. De leder i biblioteket. De leder udenfor biblioteket. De leder i Frejas hule. De leder under bordet. De leder på bordet. De leder steder, hvor en bog helt sikkert ikke kan være. \"Har du kigget i kedlen?\" spørger Astrid. \"Ja.\" Astrid stopper. \"Virkelig?\" \"Nej.\"",
              "en": "The hunt begins. They search the library. They search outside the library. They search Freya's cave. They search under the table. They search on the table. They search places where a book definitely can't be. \"Have you looked in the cauldron?\" Astrid asks. \"Yes.\" Astrid stops. \"Really?\" \"No.\""
            },
            {
              "da": "Senere sidder de på gulvet i hulen. Bøger ligger overalt. Freja ser træt ud. Astrid ser på hende. \"Hvorfor er den bog så vigtig?\" Freja tager et øjeblik om at svare. \"Den er ikke vigtig.\" Astrid venter. Freja ser ned. \"Men...\" \"Men?\" \"Den var den første bog, jeg lånte her.\" Astrid bliver stille. \"Da jeg var lille.\" Freja smiler svagt. \"Jeg læste den mange gange.\" Hun ser på bøgerne omkring sig. \"Det var derfor, jeg begyndte at læse.\" Astrid nikker langsomt. Nu forstår hun. Det handler ikke om svampe. Det handler aldrig om svampe.",
              "en": "Later they sit on the floor of the cave. Books are everywhere. Freja looks tired. Astrid looks at her. \"Why is that book so important?\" Freja takes a moment to answer. \"It's not important.\" Astrid waits. Freja looks down. \"But...\" \"But?\" \"That was the first book I borrowed here.\" Astrid falls silent. \"When I was little.\" Freja smiles faintly. \"I read it many times.\" She looks at the books around her. \"That's why I started reading.\" Astrid nods slowly. Now she understands. It's not about mushrooms. It's never about mushrooms."
            },
            {
              "da": "De leder lidt mere. Solen begynder at gå ned. Freja synker ned på en stol. \"Jeg finder den aldrig.\" Astrid ser sig omkring. Så stopper hun. \"Hvad er det?\" \"Hvad er hvad?\" Astrid peger. Oppe på en hylde. Mellem to store bøger. Noget stikker ud. Meget lidt. Freja rejser sig. Hun tager bogen ned. Så stirrer hun. Det er den. Historien om gamle svampe. Den manglende bog. Freja lukker øjnene. \"Jeg brugte tre timer på at lede efter en bog, som var i mit eget hus.\" Astrid lægger en hånd på hendes skulder. \"Det sker for de bedste.\" \"Nej.\" \"Det gør det.\" \"Nej.\" \"Det gør det virkelig.\"",
              "en": "They search a little more. The sun begins to set. Freja sinks into a chair. \"I'll never find it.\" Astrid looks around. Then she stops. \"What is it?\" \"What is what?\" Astrid points. Up on a shelf. Between two large books. Something sticks out. Very slightly. Freja stands up. She takes the book down. Then she stares. It's it. The story of old mushrooms. The missing book. Freja closes her eyes. \"I spent three hours looking for a book that was in my own house.\" Astrid puts a hand on her shoulder. \"It happens to the best of people.\" \"No.\" \"It does.\" \"No.\" \"It really does.\""
            },
            {
              "da": "Senere går de tilbage til biblioteket. Bibliotekaren tager imod bogen. Hun ser på titlen. Hun ser på Freja. Så ser hun på Astrid. \"Hm.\" \"Jeg fandt den,\" siger Freja. \"Hm.\" \"Den var i min hule.\" \"Hm.\" Astrid læner sig mod Freja. \"Hun er lidt skræmmende.\" \"Ja.\" Bibliotekaren smiler pludselig. Det er værre.",
              "en": "Later they go back to the library. The librarian accepts the book. She looks at the title. She looks at Freja. Then she looks at Astrid. \"Hm.\" \"I found it,\" Freja says. \"Hm.\" \"It was in my cave.\" \"Hm.\" Astrid leans towards Freja. \"She's a little scary.\" \"Yes.\" The librarian suddenly smiles. It's worse."
            },
            {
              "da": "Da de går hjem, er himlen orange. Solen er ved at gå ned. Freja holder bogen tæt ind til sig. Astrid går ved siden af hende. \"Er du glad nu?\" Freja nikker. \"Ja.\" Astrid smiler. Godt. Hun kan lide, når Freja smiler. Måske lidt for meget. Men det behøver vi ikke tale om. Ikke endnu. På vejen hjem tager Freja bogen frem. Inde på første side står et navn skrevet med barnlige bogstaver. Freja. Astrid ser det. \"Du var virkelig lille.\" \"Ja.\" \"Din håndskrift var forfærdelig.\" \"Ja.\" \"Den er stadig forfærdelig.\" Freja skubber hende let med skulderen. Astrid griner. Og for et øjeblik føles verden meget enkel. To venner. En gammel bog. En sti gennem skoven. Og et sted at gå hen sammen.",
              "en": "When they go home, the sky is orange. The sun is setting. Freja holds the book close to her. Astrid walks beside her. \"Are you happy now?\" Freja nods. \"Yes.\" Astrid smiles. Good. She likes it when Freja smiles. Maybe a little too much. But we don't need to talk about that. Not yet. On the way home, Freja takes out the book. Inside the first page is a name written in childish letters. Freja. Astrid sees it. \"You were really small.\" \"Yes.\" \"Your handwriting was terrible.\" \"Yes.\" \"It's still terrible.\" Freja nudges her lightly with her shoulder. Astrid laughs. And for a moment the world feels very simple. Two friends. An old book. A path through the forest. And a place to walk together."
            }
          ]
        },
        {
          "title": "Kapitel 6",
          "passages": [
            {
              "da": "Små lanterner hænger mellem husene. Musik fylder luften. Folk griner. Børn løber gennem gaderne. Festivalen er begyndt. Astrid elsker festivaler. Freja elsker stille biblioteker. På en eller anden måde er de her begge to.",
              "en": "Small lanterns hang between the houses. Music fills the air. People laugh. Children run through the streets. The festival has begun. Astrid loves festivals. Freja loves quiet libraries. Somehow they are both here."
            },
            {
              "da": "Astrid står foran Frejas dør. Hun banker. Der går et øjeblik. Så åbner døren. Astrid glemmer straks, hvad hun ville sige. Freja har en ny kjole på. Den er mørkeblå. Den passer til hendes øjne. Astrid stirrer. Meget professionelt. Meget diskret. Som en person, der bestemt ikke stirrer. \"Øh.\" Freja løfter et øjenbryn. \"Astrid?\" \"Ja.\" \"Du sagde øh.\" \"Ja.\" \"Var der mere?\" Astrid forsøger at huske sine egne tanker. Det går dårligt. \"Du ser...\" Freja venter. \"...som dig ud.\" Perfekt. Fantastisk. En succes. Astrid vil gerne kravle ned i jorden. Freja ser på hende. Så smiler hun. \"Tak.\"",
              "en": "Astrid is standing in front of Freja's door. She knocks. A moment passes. Then the door opens. Astrid immediately forgets what she wanted to say. Freja is wearing a new dress. It's dark blue. It suits her eyes. Astrid stares. Very professionally. Very discreetly. Like someone who definitely doesn't stare. \"Uh.\" Freja raises an eyebrow. \"Astrid?\" \"Yes.\" \"You said uh.\" \"Yes.\" \"Was there more?\" Astrid tries to remember her own thoughts. It's going badly. \"You look...\" Freja waits. \"...like you.\" Perfect. Fantastic. A success. Astrid wants to crawl into the ground. Freja looks at her. Then she smiles. \"Thank you.\""
            },
            {
              "da": "De går mod landsbyen. Astrid er usædvanligt stille. Freja bemærker det. \"Astrid?\" \"Hm?\" \"Er du syg?\" \"Hvad?\" \"Du har ikke sagt noget mærkeligt i fem minutter.\" \"Jeg kan være normal.\" Freja ser tvivlende ud.",
              "en": "They walk towards the village. Astrid is unusually quiet. Freja notices. \"Astrid?\" \"Hm?\" \"Are you sick?\" \"What?\" \"You haven't said anything strange for five minutes.\" \"I might be normal.\" Freja looks doubtful."
            },
            {
              "da": "Festivalen er smukkere om aftenen. Lanternerne lyser som små stjerner. Musikken kommer fra torvet. Folk danser. Nogen sælger søde kager. Astrid køber tre. Freja er ikke overrasket.",
              "en": "The festival is more beautiful in the evening. The lanterns shine like little stars. Music comes from the square. People dance. Someone sells sweet cakes. Astrid buys three. Freja is not surprised."
            },
            {
              "da": "De vandrer gennem festivalen. De ser musikere. De ser kunstnere. De ser børn, der leger. Det er hyggeligt. Meget hyggeligt. Så hører Astrid musik fra torvet. Hun stopper. \"Hm.\" Freja stopper også. \"Hvad?\" Astrid peger. Der danser folk. Par. Venner. Familier. Alle danser. Astrid ser længe på det. Meget længe. Freja får en mistanke. \"Nej.\" \"Hvad mener du?\" \"Nej.\" \"Hvad mener du med nej?\" \"Du vil spørge mig.\" \"Om hvad?\" \"Om at danse.\" Astrid bliver fornærmet. \"Jeg havde ikke tænkt mig at spørge.\" Freja nikker. \"Godt.\" Der går tre sekunder. \"Vil du danse?\" \"Der er den.\"",
              "en": "They walk through the festival. They see musicians. They see artists. They see children playing. It's cozy. Very cozy. Then Astrid hears music from the square. She stops. \"Hm.\" Freja stops too. \"What?\" Astrid points. There are people dancing. Couples. Friends. Families. Everyone dancing. Astrid looks at it for a long time. A very long time. Freja gets suspicious. \"No.\" \"What do you mean?\" \"No.\" \"What do you mean by no?\" \"You want to ask me.\" \"About what?\" \"About dancing.\" Astrid is offended. \"I didn't mean to ask.\" Freja nods. \"Okay.\" Three seconds pass. \"Do you want to dance?\" \"There it is.\""
            },
            {
              "da": "\"Jeg kan ikke danse,\" siger Freja. \"Det kan jeg heller ikke.\" \"Det hjælper ikke.\" \"Det hjælper lidt.\" Freja ser på pladsen. Så på Astrid. Så på pladsen igen. Hun sukker. \"Kun én dans.\" Astrid smiler så hurtigt, at det burde være ulovligt.",
              "en": "“I can’t dance,” Freja says. “Neither can I.” “That doesn’t help.” “It helps a little.” Freja looks at the square. Then at Astrid. Then at the square again. She sighs. “Just one dance.” Astrid smiles so quickly it should be illegal."
            },
            {
              "da": "De går ud på torvet. Musikken spiller. Astrid tilbyder sin hånd. Freja ser på den. Så tager hun den. Astrids hjerte stopper næsten. Det er meget upraktisk. Men heldigvis starter det igen. Musikken fortsætter. De begynder at danse. Hvis man er venlig. Hvis man er meget venlig. Sandheden er, at de begge er elendige. Astrid træder på Frejas fod. Freja går den forkerte vej. Astrid snubler. Freja griber hende. Astrid griber Freja. Nu står de meget tæt. Meget. Meget tæt. Begge fryser. Musikken fortsætter. Ingen af dem bevæger sig. \"Øh,\" siger Astrid. \"Ja,\" siger Freja. Ingen af dem flytter sig.",
              "en": "They go out into the square. The music is playing. Astrid offers her hand. Freya looks at it. Then she takes it. Astrid's heart almost stops. It's very inconvenient. But luckily it starts again. The music continues. They start dancing. If you're kind. If you're very kind. The truth is, they're both miserable. Astrid steps on Freya's foot. Freya goes the wrong way. Astrid trips. Freya grabs her. Astrid grabs Freya. Now they're standing very close. Very. Very close. Both freeze. The music continues. Neither of them moves. \"Uh,\" says Astrid. \"Yes,\" says Freya. Neither of them moves."
            },
            {
              "da": "En ældre kvinde går forbi. Hun ser på dem. Så ryster hun på hovedet. \"Unge mennesker.\" Astrid bliver rød. Freja bliver rød. Den ældre kvinde går videre. Hun ser meget tilfreds ud.",
              "en": "An older woman walks by. She looks at them. Then she shakes her head. \"Young people.\" Astrid turns red. Freja turns red. The older woman walks on. She looks very pleased."
            },
            {
              "da": "Til sidst lykkes det faktisk at danse lidt. Ikke godt. Men bedre. Astrid griner. Freja smiler. Lanternerne lyser over dem. Musikken fylder aftenen. Og for et øjeblik glemmer begge at være nervøse.",
              "en": "Finally, they actually manage to dance a little. Not well. But better. Astrid laughs. Freja smiles. The lanterns shine above them. The music fills the evening. And for a moment, both forget to be nervous."
            },
            {
              "da": "Senere sidder de på en bænk. Festivalen fortsætter omkring dem. Astrid holder en pose med søde kager. Freja holder en kop te. De er begge stille. Ikke en akavet stilhed. En rar stilhed. Den slags stilhed, man kun har med mennesker, man stoler på. Astrid ser op. Lanternerne bevæger sig i vinden. \"Det var sjovt.\" Freja nikker. \"Ja.\" \"Selv om vi er dårlige til at danse.\" \"Meget dårlige.\" Astrid griner. Så bliver hun stille. \"Tak fordi du kom.\" Freja ser på hende. \"Selvfølgelig.\" Astrid smiler. Et lille smil. Et ægte smil. Det får Frejas hjerte til at opføre sig mærkeligt. Hun beslutter sig for at ignorere det. Det virker ikke.",
              "en": "Later, they sit on a bench. The festival continues around them. Astrid holds a bag of sweet cakes. Freja holds a cup of tea. They are both quiet. Not an awkward silence. A nice silence. The kind of silence you only have with people you trust. Astrid looks up. The lanterns move in the wind. \"That was fun.\" Freja nods. \"Yes.\" \"Even though we're bad at dancing.\" \"Very bad.\" Astrid laughs. Then she falls silent. \"Thank you for coming.\" Freja looks at her. \"Of course.\" Astrid smiles. A small smile. A genuine smile. It makes Freja's heart act strangely. She decides to ignore it. It doesn't work."
            },
            {
              "da": "Da de går hjem, er natten mørk. Lanternerne er langt bag dem nu. Skoven er stille. Astrid går ved siden af Freja. Deres skuldre rører næsten hinanden. Næsten. Så rammer de hinanden ved et uheld. Begge siger undskyld. Samtidig. Så siger de det igen. Samtidig. Så begynder de at grine. Og resten af vejen hjem går de lidt tættere sammen. Ingen af dem nævner det. Men ingen af dem flytter sig heller.",
              "en": "When they walk home, the night is dark. The lanterns are far behind them now. The forest is quiet. Astrid walks next to Freja. Their shoulders almost touch. Almost. Then they accidentally bump into each other. Both say sorry. At the same time. Then they say it again. At the same time. Then they start laughing. And the rest of the way home they walk a little closer together. Neither of them mentions it. But neither of them moves either."
            }
          ]
        },
        {
          "title": "Kapitel 7",
          "passages": [
            {
              "da": "Sne ligger over skoven. Sne ligger på stierne. Sne ligger på taget af Frejas hule. Astrid synes, det er fantastisk. Freja synes, det er koldt.",
              "en": "Snow lies over the forest. Snow lies on the paths. Snow lies on the roof of Freya's cave. Astrid thinks it's fantastic. Freya thinks it's cold."
            },
            {
              "da": "De sidder ved pejsen. Astrid drikker te. Freja læser. Det er en normal dag. Så kommer der en banken på døren. Freja åbner. En mand fra landsbyen står udenfor. Hans næse er rød af kulde. \"Undskyld,\" siger han. \"Vi har brug for hjælp.\"",
              "en": "They are sitting by the fireplace. Astrid is drinking tea. Freja is reading. It is a normal day. Then there is a knock on the door. Freja opens. A man from the village is standing outside. His nose is red from the cold. \"Excuse me,\" he says. \"We need help.\""
            },
            {
              "da": "En lille landsby oppe i bjergene mangler medicin. Normalt er vejen let. Men sneen har gjort rejsen svær. Astrid siger ja med det samme. Selvfølgelig gør hun det. Freja siger ja tre sekunder senere. Selvfølgelig gør hun det.",
              "en": "A small village up in the mountains is short of medicine. Normally the road is easy. But the snow has made the journey difficult. Astrid says yes immediately. Of course she does. Freja says yes three seconds later. Of course she does."
            },
            {
              "da": "Næste morgen begynder de rejsen. Sne knaser under støvlerne. Luften er iskold. Astrid går forrest. Hun ser glad ud. Freja forstår det ikke. \"Hvorfor smiler du?\" \"Fordi det sner.\" \"Ja.\" \"Jeg kan lide sne.\" \"Den prøver aktivt at dræbe os.\" Astrid tænker. \"Det er en fair pointe.\"",
              "en": "The next morning they begin their journey. Snow crunches under their boots. The air is icy cold. Astrid walks in front. She looks happy. Freja doesn't understand. \"Why are you smiling?\" \"Because it's snowing.\" \"Yes.\" \"I like snow.\" \"It's actively trying to kill us.\" Astrid thinks. \"That's a fair point.\""
            },
            {
              "da": "Timerne går. De følger den smalle bjergsti. Vinden bliver stærkere. Snefnuggene flyver gennem luften. Freja trækker sin kappe tættere omkring sig. Astrid går stadig som en person uden s​e​l​v​o​p​h​o​l​d​e​l​s​e​s​d​r​i​f​t​.​",
              "en": "The hours pass. They follow the narrow mountain path. The wind grows stronger. Snowflakes fly through the air. Freja pulls her cloak tighter around her. Astrid still walks like a person without the drive for self-preservation."
            },
            {
              "da": "Så sker det. Astrids fod glider. Kun et øjeblik. Kun et lille skridt. Men det er nok. Hun mister balancen. Frejas hjerte stopper. Astrid falder ikke. Hun retter sig hurtigt op igen. Alt er fint. Alt er helt fint. Men Freja er allerede ved siden af hende. \"Astrid!\" Astrid blinker. \"Hvad?\" \"Er du okay?\" \"Ja?\" Freja ser på hende. \"Er du sikker?\" \"Ja.\" Freja undersøger hende stadig. Som om Astrid måske er gået i stykker. \"Astrid.\" \"Ja?\" \"Vær forsigtig.\" Astrid bliver stille. Meget stille. Så smiler hun. Et blødt smil. \"Okay.\"",
              "en": "Then it happens. Astrid's foot slips. Just for a moment. Just a small step. But that's enough. She loses her balance. Freja's heart stops. Astrid doesn't fall. She quickly straightens up again. Everything is fine. Everything is perfectly fine. But Freja is already next to her. \"Astrid!\" Astrid blinks. \"What?\" \"Are you okay?\" \"Yes?\" Freja looks at her. \"Are you sure?\" \"Yes.\" Freja is still examining her. As if Astrid might have broken. \"Astrid.\" \"Yes?\" \"Be careful.\" Astrid goes quiet. Very quiet. Then she smiles. A soft smile. \"Okay.\""
            },
            {
              "da": "De fortsætter. Men nu går Freja tættere på. Meget tættere på. Hvis Astrid glider igen, vil Freja være der. Hvis Astrid falder, vil Freja være der. Hvis Astrid— Nej. Astrid falder ikke. Astrid er stærk. Astrid er dygtig. Astrid er— Astrid nyser. Freja hopper næsten. \"Astrid.\" \"Det er bare et nys.\" \"Du bliver syg.\" \"Det tror jeg ikke.\" \"Astrid.\" \"Ja?\" \"Tag halstørklædet på.\" Astrid ser ned. Halstørklædet ligger allerede om hendes hals. \"...Åh.\" Freja lukker øjnene.",
              "en": "They continue. But now Freja is getting closer. Much closer. If Astrid slips again, Freja will be there. If Astrid falls, Freja will be there. If Astrid— No. Astrid won’t fall. Astrid is strong. Astrid is skilled. Astrid is— Astrid sneezes. Freja almost jumps. “Astrid.” “It’s just a sneeze.” “You’re going to get sick.” “I don’t think so.” “Astrid.” “Yes?” “Put on the scarf.” Astrid looks down. The scarf is already around her neck. “…Oh.” Freja closes her eyes."
            },
            {
              "da": "Ved solnedgang når de landsbyen. Medicin bliver afleveret. Folk takker dem. Der bliver lavet varm suppe. Astrid spiser tre skåle. Freja er ikke overrasket.",
              "en": "At sunset they reach the village. Medicine is delivered. People thank them. Hot soup is made. Astrid eats three bowls. Freja is not surprised."
            },
            {
              "da": "Den aften får de et værelse på kroen. Kun ét værelse. Kun ét. Der er to senge. Men stadig. Kun ét værelse. Astrid synes ikke, det er mærkeligt. Freja er pludselig meget interesseret i loftet.",
              "en": "That night they get a room at the inn. Only one room. Only one. There are two beds. But still. Only one room. Astrid doesn't think it's strange. Freja is suddenly very interested in the attic."
            },
            {
              "da": "Senere ligger de begge vågne. Mørket fylder rummet. Sneen falder udenfor. \"Astrid?\" \"Hm?\" \"Sover du?\" \"Nej.\" \"Okay.\" Der går et øjeblik. Så et til. Så et til. \"Astrid?\" \"Hm?\" \"Du var tæt på at falde i dag.\" Astrid vender sig om. Selv i mørket kan hun høre bekymringen i Frejas stemme. \"Jeg er okay.\" \"Jeg ved det.\" Freja holder pause. \"Men jeg kunne ikke lide det.\" Astrid bliver stille. Hun ved ikke helt hvorfor. Men de ord føles varme. Varmere end tæppet. Varmere end pejsen nedenunder. Varmere end teen. \"Undskyld.\" \"Det er ikke din skyld.\" \"Jeg skal nok passe bedre på.\" Freja nikker. Selv om Astrid ikke kan se det. \"Godt.\"",
              "en": "Later, they both lie awake. Darkness fills the room. Snow is falling outside. \"Astrid?\" \"Hm?\" \"Are you asleep?\" \"No.\" \"Okay.\" A moment passes. Then another. Then another. \"Astrid?\" \"Hm?\" \"You almost fell today.\" Astrid turns around. Even in the darkness, she can hear the concern in Freja's voice. \"I'm okay.\" \"I know.\" Freja pauses. \"But I didn't like it.\" Astrid falls silent. She doesn't quite know why. But those words feel warm. Warmer than the blanket. Warmer than the fireplace downstairs. Warmer than the tea. \"Sorry.\" \"It's not your fault.\" \"I'll be more careful.\" Freja nods. Even though Astrid can't see it. \"Good.\""
            },
            {
              "da": "Der går endnu et øjeblik. Så siger Astrid: \"Freja?\" \"Ja?\" \"Det er rart.\" \"Hvad er rart?\" \"At nogen bekymrer sig.\" Rummet bliver stille. Meget stille. Freja mærker sit hjerte slå hårdere. \"Selvfølgelig bekymrer jeg mig.\" Astrid smiler i mørket. \"Ja.\" Hun lukker øjnene. \"Godnat, Freja.\" Freja ligger vågen lidt længere. Hun stirrer op i mørket. Hun tænker på Astrid. På hendes smil. På hendes latter. På den måde hun altid banker på døren om morgenen. På den måde hulen føles tom, når hun ikke er der. Og for første gang begynder en lille tanke at vokse. En meget lille tanke. En meget farlig tanke. Den siger: Måske er det ikke normalt at tænke så meget på én person. Freja trækker tæppet op over hovedet. Det hjælper ikke. Overhovedet ikke.",
              "en": "Another moment passes. Then Astrid says: \"Freja?\" \"Yes?\" \"That's nice.\" \"What's nice?\" \"That someone cares.\" The room becomes quiet. Very quiet. Freja feels her heart beat faster. \"Of course I care.\" Astrid smiles in the darkness. \"Yes.\" She closes her eyes. \"Goodnight, Freja.\" Freja lies awake a little longer. She stares up into the darkness. She thinks of Astrid. Of her smile. Of her laughter. Of the way she always knocks on the door in the morning. Of the way the cave feels empty when she's not there. And for the first time a small thought begins to grow. A very small thought. A very dangerous thought. It says:Maybe it's not normal to think so much about one person.Freja pulls the blanket up over her head. It doesn't help. Not at all."
            }
          ]
        },
        {
          "title": "Kapitel 8",
          "passages": [
            {
              "da": "Sneen glitrer svagt i måneskinnet. Luften er kold, men stille. Freja og Astrid ligger på ryggen på et tæppe uden for kroen. De ser op. Stjernerne er mange. Meget mange. Astrid peger. \"Den der ligner en fisk.\" Freja følger hendes finger. \"Det er ikke en fisk.\" \"Det er en fisk, hvis du tror hårdt nok.\" \"Så er alt jo hvad som helst.\" \"Præcis.\" Freja sukker. Men hun smiler.",
              "en": "The snow glitters faintly in the moonlight. The air is cold, but still. Freja and Astrid lie on their backs on a blanket outside the inn. They look up. The stars are many. Very many. Astrid points. \"The one that looks like a fish.\" Freja follows her finger. \"It's not a fish.\" \"It's a fish, if you think hard enough.\" \"Then everything is anything.\" \"Exactly.\" Freja sighs. But she smiles."
            },
            {
              "da": "Der går noget tid. Ingen siger noget. Ikke fordi det er akavet. Bare fordi det ikke er nødvendigt. Astrid vender hovedet lidt. \"Freja?\" \"Hm?\" \"Tror du, stjernerne kan falde ned?\" Freja tænker. \"Nej.\" \"Ikke engang lidt?\" \"Nej.\" Astrid virker skuffet. \"Det ville ellers være pænt.\" \"Det ville være farligt.\" \"Det kan være begge dele.\" Freja svarer ikke. Hun giver hende bare et blik. Astrid griner.",
              "en": "Some time passes. No one says anything. Not because it's awkward. Just because it's not necessary. Astrid turns her head a little. \"Freja?\" \"Hm?\" \"Do you think the stars might fall?\" Freja thinks. \"No.\" \"Not even a little?\" \"No.\" Astrid seems disappointed. \"That would be nice.\" \"That would be dangerous.\" \"It could be both.\" Freja doesn't answer. She just gives her a look. Astrid laughs."
            },
            {
              "da": "Vinden bevæger sig gennem træerne. Tæppet ligger tungt over dem. Astrid trækker det lidt højere op. Freja justerer sin kappe. Og så sker det. Meget småt. Meget ubetydeligt. Astrids hånd flytter sig. Frejas hånd flytter sig samtidig. De rører hinanden. Kun fingerspidser. Kun et sekund. Men det er nok. Begge bliver stille. Meget stille. Astrid stirrer op i himlen. Freja gør det samme. Ingen flytter hånden. Ikke med det samme.",
              "en": "The wind moves through the trees. The blanket lies heavy over them. Astrid pulls it up a little higher. Freja adjusts her cloak. And then it happens. Very slightly. Very insignificantly. Astrid's hand moves. Freja's hand moves at the same time. They touch each other. Just fingertips. Just a second. But that's enough. Both of them go quiet. Very quiet. Astrid stares up at the sky. Freja does the same. No one moves their hand. Not right away."
            },
            {
              "da": "\"Din hånd er kold,\" siger Astrid til sidst. Freja blinker. \"Ja.\" \"Det er nok sneen.\" \"Det er nok fordi det er vinter.\" \"Det er nok fordi du ikke tager nok vanter på.\" \"Jeg har vanter.\" \"Du har ikke vanter nu.\" \"De er i lommen.\" \"Det hjælper ikke dine hænder.\" Freja siger ikke noget.",
              "en": "\"Your hand is cold,\" Astrid says finally. Freja blinks. \"Yes.\" \"It's probably the snow.\" \"It's probably because it's winter.\" \"It's probably because you don't wear enough mittens.\" \"I have mittens.\" \"You don't have mittens now.\" \"They're in your pocket.\" \"That won't help your hands.\" Freja doesn't say anything."
            },
            {
              "da": "Astrid vender sig lidt mere mod hende. Hendes hånd er stadig der. \"Freja?\" \"Ja?\" \"Er det okay?\" \"Ja.\" Et kort svar. For kort. Så tilføjer hun: \"Ja.\" Astrid smiler svagt. \"Okay.\" De siger ikke noget om hænderne. Men de flytter dem heller ikke.",
              "en": "Astrid turns a little more towards her. Her hand is still there. \"Freja?\" \"Yes?\" \"Is that okay?\" \"Yes.\" A short answer. Too short. Then she adds: \"Yes.\" Astrid smiles faintly. \"Okay.\" They don't say anything about the hands. But they don't move them either."
            },
            {
              "da": "Senere peger Astrid igen. \"Den der stjerne.\" \"Hvilken?\" \"Den lige over træet.\" Freja følger hendes blik. \"Ja?\" \"Den ser ensom ud.\" Freja tænker. \"Stjerner er ikke ensomme.\" \"Hvordan ved du det?\" \"Fordi de er mange.\" Astrid er stille. \"Det er ikke det samme som ikke at være ensom.\" Freja ser på hende. I mørket kan hun ikke helt aflæse hendes ansigt. \"Nej.\" Der går et øjeblik. Astrid klemmer svagt om Frejas hånd. Meget svagt. Som om hun tester, om den stadig er der. Freja klemmer tilbage. Ikke hårdt. Bare nok.",
              "en": "Later, Astrid points again. \"That star.\" \"Which one?\" \"The one just above the tree.\" Freja follows her gaze. \"Yes?\" \"It looks lonely.\" Freja thinks. \"Stars aren't lonely.\" \"How do you know?\" \"Because there are many of them.\" Astrid is silent. \"That's not the same as not being lonely.\" Freja looks at her. In the darkness, she can't quite read her face. \"No.\" A moment passes. Astrid squeezes Freja's hand weakly. Very weakly. As if testing whether it's still there. Freja squeezes back. Not hard. Just enough."
            },
            {
              "da": "\"Freja?\" \"Ja.\" \"Hvis du var en stjerne, ville du så være alene?\" Freja tænker længe. Meget længe. \"Jeg tror ikke, jeg ville være en stjerne.\" \"Hvad ville du være?\" Freja ser op. \"Noget der ikke bevæger sig så langt væk.\" Astrid bliver stille. \"Som hvad?\" Freja tøver. \"Som... et sted.\" Astrid smiler i mørket. \"Det lyder hyggeligt.\" \"Det er meningen.\"",
              "en": "\"Freja?\" \"Yes.\" \"If you were a star, would you be alone?\" Freja thinks for a long time. A very long time. \"I don't think I would be a star.\" \"What would you be?\" Freja looks up. \"Something that doesn't move that far away.\" Astrid falls silent. \"Like what?\" Freja hesitates. \"Like... somewhere.\" Astrid smiles in the darkness. \"That sounds cozy.\" \"That's the point.\""
            },
            {
              "da": "Vinden bliver lidt koldere. Astrid trækker tæppet helt op til skuldrene. Freja lægger mærke til det. Hun rykker lidt tættere på. Bare lidt. Det er ikke planlagt. Det sker bare.",
              "en": "The wind gets a little colder. Astrid pulls the blanket all the way up to her shoulders. Freja notices it. She moves a little closer. Just a little. It's not planned. It just happens."
            },
            {
              "da": "\"Freja?\" \"Hm?\" \"Jeg er glad for, at du kom med.\" Freja svarer ikke med det samme. \"Det er jeg også.\" Astrid drejer hovedet. \"Selv når det er koldt.\" \"Selv når det er koldt.\" \"Selv når vi næsten falder ned ad bjerge.\" \"Det var én gang.\" \"Det var stadig mange skridt.\" Freja smiler.",
              "en": "\"Freja?\" \"Hm?\" \"I'm glad you came along.\" Freja doesn't answer right away. \"Me too.\" Astrid turns her head. \"Even when it's cold.\" \"Even when it's cold.\" \"Even when we almost fall down mountains.\" \"That was once.\" \"That was still a lot of steps.\" Freja smiles."
            },
            {
              "da": "De ligger der længe. Stjernerne bevæger sig langsomt. Eller måske er det jorden. Ingen af dem siger det højt. Til sidst siger Astrid: \"Vi burde gøre det her igen.\" Freja lukker øjnene et øjeblik. \"Ja.\" \"Men næste gang med mindre kulde.\" \"Enig.\" \"Og flere kager.\" \"Det er ikke relevant.\" \"Det er altid relevant.\" Freja giver en lyd, der næsten er et grin.",
              "en": "They lie there for a long time. The stars move slowly. Or maybe it's the earth. Neither of them says it out loud. Finally Astrid says: \"We should do this again.\" Freja closes her eyes for a moment. \"Yes.\" \"But next time with less cold.\" \"Agreed.\" \"And more cakes.\" \"That's not relevant.\" \"It's always relevant.\" Freja makes a sound that's almost a laugh."
            },
            {
              "da": "Da de går indenfor igen, slipper ingen af dem hånden med det samme. Ikke med det samme. Bare lidt for sent. Og begge lader som om det ikke skete.",
              "en": "When they go back inside, neither of them lets go of the hand right away. Not right away. Just a little too late. And both of them pretend it didn't happen."
            }
          ]
        },
        {
          "title": "Kapitel 9",
          "passages": [
            {
              "da": "Astrid sover stadig. Hun ligger på siden. Tæppet er halvt faldet ned. Freja ser på hende. I et øjeblik gør hun ingenting. Så rejser hun sig stille.",
              "en": "Astrid is still sleeping. She is lying on her side. The blanket has half fallen down. Freja looks at her. For a moment she does nothing. Then she gets up quietly."
            },
            {
              "da": "Udenfor er morgenen grå. Sneen er stadig der, men den er hårdere nu. Som om natten har trykket den ned. Freja går lidt væk fra kroen. Bare lidt. Hun stopper ved kanten af stien. Og opdager noget mærkeligt. Der er stille. Ikke bare normalt stille. Men tomt stille. Hun vender sig. Kroen er der stadig. Alt er som det plejer. Men det føles anderledes. Hun forstår ikke hvorfor.",
              "en": "Outside, the morning is gray. The snow is still there, but it's harder now. As if the night has pressed it down. Freja walks a little away from the inn. Just a little. She stops at the edge of the path. And notices something strange. It's quiet. Not just normal quiet. Butplotquiet. She turns. The inn is still there. Everything is as usual. But it feels different. She doesn't understand why."
            },
            {
              "da": "Astrid vågner senere. Hun sætter sig op med det samme. Ser sig omkring. \"Freja?\" Ingen svar. Hun går udenfor. \"Freja?\" Hendes stemme forsvinder i luften. Ingen svar. Astrid står stille. Hun burde ikke bekymre sig. Freja er sikkert bare gået en tur. Freja går altid ture. Det er det, Freja gør. Men noget i Astrids bryst strammer sig alligevel. Hun bryder sig ikke om det.",
              "en": "Astrid wakes up later. She sits up immediately. Looks around. \"Freja?\" No answer. She goes outside. \"Freja?\" Her voice disappears into thin air. No answer. Astrid stands still. She shouldn't worry. Freja has probably just gone for a walk. Freja always goes for walks. That's what Freja does. But something in Astrid's chest tightens anyway. She doesn't like it."
            },
            {
              "da": "Hun finder hende ved skovkanten. Freja står bare og ser ud. \"Der er du,\" siger Astrid. Freja vender sig. \"Ja.\" \"Jeg troede du var væk.\" \"Jeg er ikke væk.\" Astrid nikker hurtigt. \"Godt.\" Der går et øjeblik. Ingen af dem bevæger sig. Så siger Freja: \"Jeg skulle bare tænke.\" \"På hvad?\" Freja svarer ikke med det samme. Så: \"Ingenting.\" Astrid accepterer det. Men hun tror ikke helt på det.",
              "en": "She finds her at the edge of the forest. Freja just stands there looking out. \"There you are,\" Astrid says. Freja turns. \"Yes.\" \"I thought you were gone.\" \"I'm not gone.\" Astrid nods quickly. \"Good.\" A moment passes. Neither of them moves. Then Freja says, \"I just had to think.\" \"About what?\" Freja doesn't answer right away. Then: \"Nothing.\" Astrid accepts it. But she doesn't quite believe it."
            },
            {
              "da": "De går tilbage sammen. Sneen knaser under deres støvler. Astrid taler mere end normalt. Om vejret. Om kager. Om en fugl hun så. Freja lytter. Men hun siger mindre end normalt. Meget mindre. Og Astrid lægger mærke til det. Selv hvis hun ikke ved hvad det betyder Senere sidder de ved bordet. Te mellem dem. Freja læser. Astrid prøver at tegne noget i bordets støv. Hun tegner en drage. Den ligner ikke en drage. Den ligner et meget forvirret får. \"Freja?\" \"Hm?\" \"Er du træt?\" Freja blinker. \"Nej.\" \"Du virker træt.\" \"Jeg er bare… stille.\" Astrid nikker. Det ord forstår hun ikke helt. Men hun kan mærke det.",
              "en": "They walk back together. The snow crunches under their boots. Astrid talks more than usual. About the weather. About cakes. About a bird she saw. Freja listens. But she says less than usual. Much less. And Astrid notices it. Even if she doesn't know what it means.Later they sit at the table. Tea between them. Freja reads. Astrid tries to draw something in the dust on the table. She draws a dragon. It doesn't look like a dragon. It looks like a very confused sheep. \"Freja?\" \"Hm?\" \"Are you tired?\" Freja blinks. \"No.\" \"You seem tired.\" \"I'm just... quiet.\" Astrid nods. She doesn't quite understand that word. But she can feel it."
            },
            {
              "da": "Freja lukker bogen. \"Du sagde mit navn i søvne.\" Astrid stopper. \"Gjorde jeg?\" \"Ja.\" \"Hvad sagde jeg?\" Freja tøver. \"Ikke noget vigtigt.\" Astrid venter. Freja fortsætter ikke.",
              "en": "Freja closes the book. “You said my name in your sleep.” Astrid stops. “Did I?” “Yes.” “What did I say?” Freja hesitates. “Nothing important.” Astrid waits. Freja doesn’t continue."
            },
            {
              "da": "Der går lang tid. Regnen er væk. Sneen udenfor skinner i solen. Men indenfor føles luften tung. Ikke dårlig. Bare… anderledes. Astrid bryder stilheden. \"Freja.\" \"Ja?\" \"Når du ikke er her… føles det forkert.\" Freja ser op med det samme. \"Forkert?\" \"Ja.\" Astrid tænker. \"Som om noget mangler.\" Freja bliver stille. Meget stille. \"Det er bare fordi vi har været sammen meget.\" Astrid nikker. \"Ja. Det er nok det.\" Men hun lyder ikke overbevist. Og det gør Freja heller ikke.",
              "en": "A long time passes. The rain is gone. The snow outside is shining in the sun. But inside the air feels heavy. Not bad. Just… different. Astrid breaks the silence. \"Freja.\" \"Yes?\" \"When you're not here… it feels wrong.\" Freja looks up immediately. \"Wrong?\" \"Yes.\" Astrid thinks. \"Like something's missing.\" Freja goes quiet. Very quiet. \"It's just because we've been together a lot.\" Astrid nods. \"Yes. That's probably it.\" But she doesn't sound convinced. And neither does Freja."
            },
            {
              "da": "Senere går de en tur igen. Side om side. Lidt tættere end nødvendigt. Som altid. Astrid kigger på hende. \"Freja?\" \"Ja.\" \"Er det normalt at savne nogen, selv når de lige har været der?\" Freja svarer ikke med det samme. Så siger hun: \"Jeg ved det ikke.\" Astrid nikker. \"Okay.\" De går videre. Og for første gang er stilheden mellem dem ikke tom. Den er fyldt med noget, ingen af dem har et navn for endnu. Men begge kan mærke det. Meget tydeligt.",
              "en": "Later they go for a walk again. Side by side. A little closer than necessary. As always. Astrid looks at her. \"Freja?\" \"Yes.\" \"Is it normal to miss someone, even when they've just been there?\" Freja doesn't answer right away. Then she says, \"I don't know.\" Astrid nods. \"Okay.\" They walk on. And for the first time, the silence between them isn't empty. It's filled with something neither of them has a name for yet. But they can both feel it. Very clearly."
            }
          ]
        },
        {
          "title": "Kapitel 10",
          "passages": [
            {
              "da": "Ikke voldsomt. Bare stille regn. Den slags regn, der gør alt blødt. Astrid står foran Frejas dør. Hun banker ikke. Hun står bare. Så åbner døren. Freja ser på hende. Et øjeblik siger ingen noget. Så: \"Du kom.\" \"Ja.\" \"Det regner.\" \"Ja.\" Astrid smiler svagt. \"Jeg ved det.\" Freja træder til side. Astrid går ind. Døren lukker bag hende.",
              "en": "Not heavy. Just quiet rain. The kind of rain that makes everything soft. Astrid stands in front of Freja's door. She doesn't knock. She just stands. Then opens the door. Freja looks at her. For a moment no one says anything. Then: \"You came.\" \"Yes.\" \"It's raining.\" \"Yes.\" Astrid smiles faintly. \"I know.\" Freja steps aside. Astrid goes in. The door closes behind her."
            },
            {
              "da": "Der er te. Selvfølgelig er der te. Freja sætter kopperne på bordet. Astrid sætter sig. Det er stille. Men ikke som før. Ikke som “roligt”. Mere som “noget venter”. Freja sætter sig overfor hende. De drikker. Ingen siger noget. Så siger Astrid: \"Jeg tænkte på noget.\" Freja løfter blikket. \"Farligt.\" Astrid griner kort. \"Ja.\" Hun ser ned i sin kop. \"Når du ikke er der…\" Freja bliver stille med det samme. \"...så føles det mærkeligt.\" Freja siger ikke noget. Astrid fortsætter. \"Ikke bare lidt mærkeligt.\" \"Men… forkert.\" Freja holder koppen lidt for hårdt. \"Jeg forstår ikke.\" Astrid nikker. \"Det gør jeg heller ikke.\" Pause. Regnen udenfor. Te der damper. \"Freja?\" \"Ja.\" Astrid kigger op. Meget direkte. \"Jeg tror, jeg kan lide dig.\" Stilhed. Ikke tom stilhed. Tung stilhed. Frejas kop står stille i luften. Hun sætter den langsomt ned. \"Du… kan lide mig?\" \"Ja.\" Astrid blinker. \"Ikke bare som… te.\" \"Ikke bare som drager.\" \"Ikke bare som at sidde fast i hytter i regn.\" Freja åbner munden. Lukker den igen. Hun prøver igen. \"Jeg…\" Hun stopper. Ser væk. Ser tilbage. \"Jeg tror… jeg har det på samme måde.\" Astrid stirrer. \"På samme måde som hvad?\" Freja sukker stille. \"Som dig.\" Der går et sekund. To. Så griner Astrid. Lidt chokeret. Lidt lettet. Lidt helt væk. \"Det er en dårlig forklaring.\" \"Jeg ved det.\"",
              "en": "There is tea. Of course there is tea. Freja puts the cups on the table. Astrid sits down. It is quiet. But not like before. Not like “calm”. More like “something is waiting”. Freja sits down opposite her. They drink. No one says anything. Then Astrid says: “I was thinking about something.” Freja looks up. “Dangerous.” Astrid laughs briefly. “Yes.” She looks down into her cup. “When you’re not there…” Freja immediately falls silent. “…it feels strange.” Freja doesn’t say anything. Astrid continues. “Not just a little strange.” “But… wrong.” Freja holds the cup a little too tightly. “I don’t understand.” Astrid nods. “Neither do I.” Pause. The rain outside. Steaming tea. “Freja?” “Yes.” Astrid looks up. Very direct. “I think I like you.” Silence. Not empty silence. Heavy silence. Freja’s cup stands still in the air. She slowly puts it down. “You… like me?” “Yes.” Astrid blinks. “Not just like… tea.” “Not just like dragons.” “Not just like being stuck in huts in the rain.” Freja opens her mouth. Closes it again. She tries again. “I…” She stops. Looks away. Looks back. “I think… I feel the same way.” Astrid stares. “The same way as what?” Freja sighs quietly. “Like you.” A second passes. Two. Then Astrid laughs. A little shocked. A little relieved. A little completely lost. “That’s a poor explanation.” “I know.”"
            },
            {
              "da": "Der går endnu et øjeblik. Så rejser Astrid sig. Langsomt. Freja gør det samme. De står nu meget tæt. For tæt til at lade som ingenting. \"Freja?\" \"Ja?\" \"Er det her… mærkeligt?\" \"Ja.\" \"Godt.\" \"Godt?\" \"Ja.\" Astrid tager en lille pause. \"Fordi jeg troede, det kun var mig.\" Freja ser på hende. \"Det troede jeg også.\"",
              "en": "Another moment passes. Then Astrid stands up. Slowly. Freja does the same. They are now standing very close. Too close to pretend like nothing happened. \"Freja?\" \"Yes?\" \"Is this… strange?\" \"Yes.\" \"Good.\" \"Good?\" \"Yes.\" Astrid pauses a little. \"Because I thought it was just me.\" Freja looks at her. \"I thought so too.\""
            },
            {
              "da": "Der er et øjeblik, hvor ingen bevæger sig. Så løfter Astrid hånden. Hun stopper halvvejs. Ser på Freja. \"Er det okay?\" Freja nikker. Meget lidt. \"Ja.\" Astrids hånd rammer Frejas kind. Forsigtigt. Som om hun tester verden. Freja lukker øjnene et sekund. Så læner hun sig bare lidt frem. Og så er der ikke længere afstand. Ikke rigtig. Bare stilhed. Bare varme. Bare en kop te, der bliver kold på bordet.",
              "en": "There is a moment when no one moves. Then Astrid raises her hand. She stops halfway. Looks at Freja. \"Is that okay?\" Freja nods. Very slightly. \"Yes.\" Astrid's hand touches Freja's cheek. Carefully. As if testing the world. Freja closes her eyes for a second. Then she leans forward just a little. And then there is no more distance. Not really. Just silence. Just warmth. Just a cup of tea getting cold on the table."
            },
            {
              "da": "Da de trækker sig lidt fra hinanden igen, griner Astrid lavt. \"Det tog lang tid.\" Freja nikker. \"Meget lang tid.\" \"Vi er dårlige til det her.\" \"Meget dårlige.\" Astrid smiler. \"Skal vi blive bedre?\" Freja ser på hende. \"Ja.\" Uden tvivl denne gang. Uden tøven. Uden bøger, drager eller regn til at forklare det. Bare ja. Og udenfor fortsætter regnen stille. Som om verden giver dem lidt privatliv.",
              "en": "As they pull apart again, Astrid laughs softly. \"It took a long time.\" Freya nods. \"A very long time.\" \"We're bad at this.\" \"Very bad.\" Astrid smiles. \"Are we going to get better?\" Freya looks at her. \"Yes.\" Without a doubt this time. Without hesitation. Without books, dragons, or rain to explain it. Just yes. And outside, the rain continues quietly. As if the world is giving them a little privacy."
            }
          ]
        },
        {
          "title": "Kapitel 11",
          "passages": [
            {
              "da": "Sollys på gulvet. Ingen regn. Ingen sne. Bare lys. Astrid vågner først. Freja ligger stadig og sover. Astrid sætter sig op. Ser på hende. Længe. Hun smiler lidt. Som om hun stadig ikke helt tror på, at det er virkeligt. Freja åbner øjnene langsomt. \"Godmorgen.\" \"Godmorgen.\" Stilhed. Men anderledes stilhed nu. Ikke afstand. Bare ro. Freja sætter sig op. De sidder overfor hinanden i sengen et øjeblik. Ingen af dem bevæger sig væk. Det er nyt.",
              "en": "Sunlight on the floor. No rain. No snow. Just light. Astrid wakes up first. Freja is still sleeping. Astrid sits up. Looks at her. Long. She smiles a little. As if she still doesn't quite believe it's real. Freja opens her eyes slowly. \"Good morning.\" \"Good morning.\" Silence. But a different silence now. Not distance. Just calm. Freja sits up. They sit opposite each other in bed for a moment. Neither of them moves away. It's new."
            },
            {
              "da": "Senere sidder de ved bordet. Te igen. Selvfølgelig te. Astrid drejer sin kop lidt rundt. \"Freja?\" \"Ja.\" \"Er det mærkeligt?\" Freja tænker. \"Nej.\" \"Ikke mere?\" \"Nej.\" Astrid nikker langsomt. \"Godt.\" Der går et øjeblik. Så siger Freja: \"Jeg har tænkt på det hele natten.\" \"Det lyder usundt.\" \"Det var ikke usundt.\" Astrid smiler. \"Okay.\" Freja ser ned i sin kop. \"Det føles bare… rigtigt.\" Astrid bliver stille. \"Ja.\"",
              "en": "Later they sit at the table. Tea again. Of course tea. Astrid swirls her cup around a bit. \"Freja?\" \"Yes.\" \"Is that strange?\" Freja thinks. \"No.\" \"Not anymore?\" \"No.\" Astrid nods slowly. \"Good.\" A moment passes. Then Freja says: \"I've been thinking about it all night.\" \"That sounds unhealthy.\" \"It wasn't unhealthy.\" Astrid smiles. \"Okay.\" Freja looks down into her cup. \"It just feels... right.\" Astrid falls silent. \"Yes.\""
            },
            {
              "da": "De går en tur senere. Skoven er den samme. Men ikke helt. Astrid går lidt tættere på Freja end før. Ikke forsigtigt længere. Bare naturligt. Freja flytter sig ikke væk. Hun går tættere også. Uden at sige det.",
              "en": "They go for a walk later. The forest is the same. But not quite. Astrid walks a little closer to Freja than before. Not cautiously anymore. Just naturally. Freja doesn't move away. She walks closer too. Without saying it."
            },
            {
              "da": "Ved en lille bro stopper de. Vandet under dem er langsomt. Astrid læner sig op ad rækværket. Freja står ved siden af hende. Der går et øjeblik. Så siger Astrid: \"Freja.\" \"Ja.\" Astrid kigger på hende. Ikke væk. Ikke ned. Bare på hende. \"Jeg elsker dig.\" Freja blinker. En gang. To gange. Så bliver hun stille. Meget stille. Så siger hun: \"Jeg ved det.\" Astrid griner. \"Det var ikke det rigtige svar.\" Freja ryster lidt på hovedet. \"Jeg ved det.\" Pause. Så: \"Jeg elsker dig også.\"",
              "en": "At a small bridge they stop. The water below them is slow. Astrid leans against the railing. Freja stands next to her. A moment passes. Then Astrid says: \"Freja.\" \"Yes.\" Astrid looks at her. Not away. Not down. Just at her. \"I love you.\" Freja blinks. Once. Twice. Then she goes quiet. Very quiet. Then she says: \"I know.\" Astrid laughs. \"That wasn't the right answer.\" Freja shakes her head a little. \"I know.\" Pause. Then: \"I love you too.\""
            },
            {
              "da": "Det er ikke dramatisk. Ingen musik. Ingen verden der stopper. Bare en bro. Et stykke vand. To mennesker, der endelig siger det rigtigt. Astrid læner sig lidt frem. Freja gør det samme. Denne gang er der ingen tvivl. Ingen spørgsmål. Ingen “må jeg?” Bare dem. Sammen. Som de hele tiden har været.",
              "en": "It's not dramatic. No music. No world stopping. Just a bridge. A stretch of water. Two people finally saying it right. Astrid leans forward a little. Freja does the same. This time there's no doubt. No questions. No “can I?” Just them. Together. As they've always been."
            },
            {
              "da": "Og langt senere, når de går hjem, siger Astrid: \"Det her var faktisk ret nemt.\" Freja svarer: \"Det tog os bare lang tid at starte.\" Astrid griner. \"Typisk os.\" \"Ja.\" Og de går videre. Samme sti. Samme skov. Men ikke samme afstand.",
              "en": "And much later, when they're walking home, Astrid says, \"This was actually pretty easy.\" Freja replies, \"It just took us a long time to start.\" Astrid laughs. \"Typical of us.\" \"Yeah.\" And they keep going. Same path. Same forest. But not the same distance."
            }
          ]
        }
      ]
    }
  ]
};
